### ISSUE TITLE
Service WifiIntentService has leaked IntentReceiver

### ISSUE THREAD

**Issue by kzaikin** [yandex-qatools/android-wifitool#8]
1. Run wifitool
2. See logcat

D/WifiTool(30606): Start connection
D/WifiTool(30606): WIFI_STATE_ENABLED
D/WifiTool(30606): Get configured network id...
D/WifiTool(30606): Configured network found
E/ActivityThread(30606): Service ru.yandex.qatools.wifitool.WifiIntentService has leaked IntentReceiver ru.yandex.qatools.wifitool.ConnectivityMonitor$3@26179ba0 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread(30606): android.app.IntentReceiverLeaked: Service ru.yandex.qatools.wifitool.WifiIntentService has leaked IntentReceiver ru.yandex.qatools.wifitool.ConnectivityMonitor$3@26179ba0 that was originally registered here. Are you missing a call to unregisterReceiver()?
E/ActivityThread(30606): 	at ru.yandex.qatools.wifitool.ConnectivityMonitor.register(ConnectivityMonitor.java:115)
E/ActivityThread(30606): 	at ru.yandex.qatools.wifitool.ConnectivityMonitor.access$100(ConnectivityMonitor.java:23)
E/ActivityThread(30606): 	at ru.yandex.qatools.wifitool.ConnectivityMonitor$1.then(ConnectivityMonitor.java:60)
E/ActivityThread(30606): 	at ru.yandex.qatools.wifitool.ConnectivityMonitor$1.then(ConnectivityMonitor.java:52)
E/ActivityThread(30606): 	at ru.yandex.qatools.wifitool.NetworkManager.startConnection(NetworkManager.java:63)
E/ActivityThread(30606): 	at ru.yandex.qatools.wifitool.IntentProcessor.handle(IntentProcessor.java:25)
E/ActivityThread(30606): 	at ru.yandex.qatools.wifitool.WifiIntentService.onHandleIntent(WifiIntentService.java:17)
I/WifiTool:Success(30606): Connected

**Comment by kzaikin** [comment]
Looks like it was some early build. Can not reproduce
